title: Every ms count
email: xt6.thomas.genin@gmail.com
description: |
  Every ms count and every bytes count, until the don't 
baseurl: ''
url: 'http://genintho.github.io'
github_username: genintho
markdown: kramdown
permalink: '/:title'
