# Site settings
title: Thomas genin
email: xt6.thomas.genin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Every bytes count.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://genintho.github.io"
#url: "http://0.0.0.0:4000"
#twitter_username: jekyllrb
github_username:  genintho

# Build settings
markdown: kramdown
